# Rule Configuration
options:
  formatter: stylish
files:
  include: 'assets/styles/**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 0

  # Mixins
  mixins-before-declarations:
    - 2
    - exclude:
        - breakpoint
        - mq

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks:
    - 1
    - include: true
  single-line-per-selector: 1

  # Disallows
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-warn: 1
  no-color-keywords: 1
  no-invalid-hex: 1
  no-css-comments: 1
  no-color-literals:
    - 1
    - allow-rgba: false

  # Style Guide
  border-zero: 1
  clean-import-paths:
    - 1
    - leading-underscore: false
    - filename-extension: false
  empty-args:
    - 1
    - include: true

  hex-length: 1
  hex-notation:
    - 2
    - style: lowercase
  indentation:
    - 2
    - size: 4
  leading-zero: 1
  nesting-depth:
    - 2
    - max-depth: 5
  property-sort-order: 1
  quotes:
    - 1
    - style: double
  variable-for-property: 1
  zero-unit:
    - 1
    - include: false

  # Inner Spacing
  space-after-comma: 1
  space-before-colon:
    - 2
    -
      include: false
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
